### ISSUE TITLE
每一步都是照着你写的来，但是workflow run failed

### ISSUE THREAD

**Issue by lsy1973** [BeiyanYunyi/AntiFacistIndoctrination#1]
我真的哭死

**Comment by BeiyanYunyi** [comment]
……我也没法排错啊，可能的问题有很多，比如 cookie 获取错了，比如你 `AFI_COOKIE` 填了 `abeadfsgd` 而不是 `laravel_session=abeadfsgd`（等于号前面的要保留）

如果你有 rust 编译环境，那倒是可以输出一些 debug 信息

**Comment by lsy1973** [comment]
感谢回复！问题自己找到了，需要在江苏共青团公众号获取cookie，而不是自己学校的公众号上获取，已成功运行

**Comment by BeiyanYunyi** [comment]
所以六个 fork 的人里一个 star 我的都没有（

快 star 我
