### ISSUE TITLE
Is there an alternative way to get cookies?

### ISSUE THREAD

**Issue by Flyfish233** [BeiyanYunyi/AntiFacistIndoctrination#2]
`http://yuzai.xyz/%e9%9d%92%e5%b9%b4%e5%a4%a7%e5%ad%a6%e4%b9%a0%e6%8a%93%e5%8c%85%e6%95%99%e7%a8%8b/`

该链接已经 404，也没有在 Web Archive 上找到可用副本。现在有什么办法可用于获取 cookies 和 token 吗？

**Comment by BeiyanYunyi** [comment]
使用 HTTPCanary 进行抓包即可。
