### ISSUE TITLE
cookie教程没了

### ISSUE THREAD

**Issue by Yezhoubing** [BeiyanYunyi/AntiFacistIndoctrination#4]
获取cookie教程没了，还有别的教程吗

**Comment by BeiyanYunyi** [comment]
https://web.archive.org/web/20230306140515/https://yuzaii.github.io/archives/c59a0c1a.html

我不是给了备份链接吗？

**Comment by BeiyanYunyi** [comment]
![图片](https://user-images.githubusercontent.com/14120445/224523655-6202fa19-7106-4c79-b713-97741ee4ba40.png)

不对啊，这里的两个链接都是可用的

**Comment by Yezhoubing** [comment]
![image](https://user-images.githubusercontent.com/58723751/224527711-d02abf4f-47a5-46af-9713-d64863eb02e5.png)
是这个视频挂了

**Comment by BeiyanYunyi** [comment]
> 是这个视频挂了

备份链接里面的还在
